# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'CellMate_main.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_UiMain(object):
    def setupUi(self, UiMain):
        UiMain.setObjectName("UiMain")
        UiMain.resize(1071, 992)
        self.horizontalLayout = QtWidgets.QHBoxLayout(UiMain)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.btn_selectFilesToAnalyze = QtWidgets.QPushButton(UiMain)
        self.btn_selectFilesToAnalyze.setObjectName("btn_selectFilesToAnalyze")
        self.verticalLayout.addWidget(self.btn_selectFilesToAnalyze)
        self.lbl_filesToAnalyze = QtWidgets.QLabel(UiMain)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lbl_filesToAnalyze.setFont(font)
        self.lbl_filesToAnalyze.setObjectName("lbl_filesToAnalyze")
        self.verticalLayout.addWidget(self.lbl_filesToAnalyze)
        self.listWidget_filesToAnalyze = QtWidgets.QListWidget(UiMain)
        self.listWidget_filesToAnalyze.setObjectName("listWidget_filesToAnalyze")
        self.verticalLayout.addWidget(self.listWidget_filesToAnalyze)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.btn_selectOutDir = QtWidgets.QPushButton(UiMain)
        self.btn_selectOutDir.setObjectName("btn_selectOutDir")
        self.verticalLayout_4.addWidget(self.btn_selectOutDir)
        self.outlabel = QtWidgets.QLabel(UiMain)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.outlabel.setFont(font)
        self.outlabel.setObjectName("outlabel")
        self.verticalLayout_4.addWidget(self.outlabel)
        self.listWidget_outDir = QtWidgets.QListWidget(UiMain)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listWidget_outDir.sizePolicy().hasHeightForWidth())
        self.listWidget_outDir.setSizePolicy(sizePolicy)
        self.listWidget_outDir.setBaseSize(QtCore.QSize(0, 0))
        self.listWidget_outDir.setObjectName("listWidget_outDir")
        self.verticalLayout_4.addWidget(self.listWidget_outDir)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_4.addItem(spacerItem)
        self.settingslabel = QtWidgets.QLabel(UiMain)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.settingslabel.setFont(font)
        self.settingslabel.setObjectName("settingslabel")
        self.verticalLayout_4.addWidget(self.settingslabel)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.output_unitBox = QtWidgets.QComboBox(UiMain)
        self.output_unitBox.setEditable(False)
        self.output_unitBox.setObjectName("output_unitBox")
        self.output_unitBox.addItem("")
        self.output_unitBox.addItem("")
        self.output_unitBox.addItem("")
        self.verticalLayout_3.addWidget(self.output_unitBox)
        self.distance = QtWidgets.QSpinBox(UiMain)
        self.distance.setProperty("value", 15)
        self.distance.setObjectName("distance")
        self.verticalLayout_3.addWidget(self.distance)
        self.lineThickens = QtWidgets.QSpinBox(UiMain)
        self.lineThickens.setProperty("value", 2)
        self.lineThickens.setObjectName("lineThickens")
        self.verticalLayout_3.addWidget(self.lineThickens)
        self.vector_scaler = QtWidgets.QSpinBox(UiMain)
        self.vector_scaler.setProperty("value", 20)
        self.vector_scaler.setObjectName("vector_scaler")
        self.verticalLayout_3.addWidget(self.vector_scaler)
        self.scalebar_ceckBox = QtWidgets.QCheckBox(UiMain)
        self.scalebar_ceckBox.setText("")
        self.scalebar_ceckBox.setChecked(True)
        self.scalebar_ceckBox.setObjectName("scalebar_ceckBox")
        self.verticalLayout_3.addWidget(self.scalebar_ceckBox)
        self.scalebarLength_box = QtWidgets.QSpinBox(UiMain)
        self.scalebarLength_box.setProperty("value", 10)
        self.scalebarLength_box.setObjectName("scalebarLength_box")
        self.verticalLayout_3.addWidget(self.scalebarLength_box)
        self.channel_selectBox = QtWidgets.QSpinBox(UiMain)
        self.channel_selectBox.setMinimum(1)
        self.channel_selectBox.setMaximum(2)
        self.channel_selectBox.setObjectName("channel_selectBox")
        self.verticalLayout_3.addWidget(self.channel_selectBox)
        self.gridLayout_2.addLayout(self.verticalLayout_3, 0, 1, 1, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtWidgets.QLabel(UiMain)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(UiMain)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.label_4 = QtWidgets.QLabel(UiMain)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_2.addWidget(self.label_4)
        self.label_5 = QtWidgets.QLabel(UiMain)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_2.addWidget(self.label_5)
        self.label_7 = QtWidgets.QLabel(UiMain)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_2.addWidget(self.label_7)
        self.label_8 = QtWidgets.QLabel(UiMain)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_2.addWidget(self.label_8)
        self.label = QtWidgets.QLabel(UiMain)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.gridLayout_2.addLayout(self.verticalLayout_2, 0, 0, 1, 1)
        self.verticalLayout_4.addLayout(self.gridLayout_2)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_4.addItem(spacerItem1)
        self.loglabel = QtWidgets.QLabel(UiMain)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.loglabel.setFont(font)
        self.loglabel.setObjectName("loglabel")
        self.verticalLayout_4.addWidget(self.loglabel)
        self.logOutput = QtWidgets.QTextEdit(UiMain)
        self.logOutput.setReadOnly(True)
        self.logOutput.setObjectName("logOutput")
        self.verticalLayout_4.addWidget(self.logOutput)
        self.btn_run = QtWidgets.QPushButton(UiMain)
        self.btn_run.setObjectName("btn_run")
        self.verticalLayout_4.addWidget(self.btn_run)
        self.horizontalLayout.addLayout(self.verticalLayout_4)

        self.retranslateUi(UiMain)
        QtCore.QMetaObject.connectSlotsByName(UiMain)

    def retranslateUi(self, UiMain):
        _translate = QtCore.QCoreApplication.translate
        UiMain.setWindowTitle(_translate("UiMain", "Form"))
        self.btn_selectFilesToAnalyze.setText(_translate("UiMain", "Select input folder"))
        self.lbl_filesToAnalyze.setText(_translate("UiMain", "Files to analyze:"))
        self.btn_selectOutDir.setText(_translate("UiMain", "Select output folder"))
        self.outlabel.setText(_translate("UiMain", "Output folder:"))
        self.settingslabel.setText(_translate("UiMain", "Visual representation of flow vectors:"))
        self.output_unitBox.setItemText(0, _translate("UiMain", "um/min"))
        self.output_unitBox.setItemText(1, _translate("UiMain", "um/h"))
        self.output_unitBox.setItemText(2, _translate("UiMain", "um/s"))
        self.label_2.setText(_translate("UiMain", "Output unit"))
        self.label_3.setText(_translate("UiMain", "Distance between vectors (pixels)"))
        self.label_4.setText(_translate("UiMain", "Vector line thicknes (pixels)"))
        self.label_5.setText(_translate("UiMain", "Vector length scaler"))
        self.label_7.setText(_translate("UiMain", "Draw scale bar"))
        self.label_8.setText(_translate("UiMain", "Scale bar length (in selected units)"))
        self.label.setText(_translate("UiMain", "Channel to analyze"))
        self.loglabel.setText(_translate("UiMain", "Analysis log:"))
        self.btn_run.setText(_translate("UiMain", "Run..."))

